# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,0x0,1
monitor=desc:Lenovo Group Limited LEN X24A U38HPD31,1920x1080,auto-left,0.833333 #thinkvision
monitor=HDMI-A-1,preferred,auto-right,0.833333,transform,1 #vertical
#monitor=desc:Acer Technologies KB242HYL TM1EE0048511,1920x1080,auto-up,0.833333
monitor=desc:Samsung Electric Company C24F390 HTQJ405956,preferred,auto-left,0.833333 #home
monitor=desc:HP Inc. HP E24 G4 CN41302SN4,preferred,auto-right,0.833333,transform,3
